export const svgIcons = [
  "brand-twitter",
  "brand-linkedin",
  "brand-facebook",
  "brand-telegram",
  "brand-zalo",
  "brand-telegram",
  "outline-clock",
  "chevron-right",
  "chevron-left",
  "chevron-down",
  "chevron-up",
  "close-outline",
  "facebook",
  "google",
  "github",
] as const;
