name: techmely

services:
  handbook:
    build:
      context: .
      tags:
        - "registry.gitlab.com/techmely/handbook:0.0.0-rc.0"
      args:
        - NEXT_PUBLIC_APP_VERSION=0.0.0-rc.0
        - NODE_ENV=production
    ports:
      - "5000:5000"