name: techmely

services:
  handbook:
    env_file: .env
    build:
      context: .
      tags:
        - "registry.gitlab.com/techmely/handbook:0.0.2"
    network_mode: bridge
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"