name: techmely

services:
  handbook:
    env_file: .env
    build:
      context: .
      tags:
        - "registry.gitlab.com/techmely/handbook:0.0.1"
    network_mode: bridge
    ports:
      - "${PORT}:${PORT}"